### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by Jiffies-Duke** [mchampaneri/go-sciter-example#1]
![bug](https://user-images.githubusercontent.com/19168838/51082866-412d0900-174a-11e9-970e-5abffce8e8d8.PNG)
there may be a bug in "04-CallGoFunctionFromTIscript/main.go". I input two numbers in input boxes, and get the sum of 0. 
the code:
func Sum(vals ...*sciter.Value) *sciter.Value {
    ...
    fmt.Println(val.Int())  // it is 0, whatever the input is
   ...
i add a line of "fmt.Println(val)", which shows the number I input. So I thought  val.Int() turns the input text wrongly into 0.

**Comment by c-smile** [comment]
Try this change: https://github.com/mchampaneri/go-sciter-example/compare/master...c-smile:patch-1
